#' Add_RegQuant
#'
#' @param prob
#' A numeric vector with no missing data with the probabilities (between 0 and 1).
#' @param reg_par
#' A 6-column and 1-row `data.frame` as that generated by `reg_par()`.
#'  * 1st column is the mu0 parameter,
#'  * 2nd is the mu1 parameter,
#'  * 3rd is the mu2 parameter,
#'  * 4th is the sigma0 parameter,
#'  * 5th is the sigma1 parameter,
#' @param site_temp
#' A vector or 1-column matrix with site's air temperature (original) data.
#' @param n.year
#' A single number describing the number of the year that the time-varying parameters
#' should be calculated. For example, if the users need to calculated the parameters
#' for the first year n.year is set to 1.
#' @export
#' @importFrom extRemes qevd
#' @examples
#' prob <- c(0.8,0.85,0.90,0.92,0.93,0.94,0.95,0.97,0.99)
#' best_model <- best_sites
#' reg_par <- reg_par(best_model=best_model)
#' RegQuant <- Add_RegQuant(prob=prob,
#'                   reg_par=reg_par,
#'                   site_temp=dataset$station1,
#'                   n.year=30)

Add_RegQuant <- function(prob,
                         reg_par,
                         site_temp,
                         n.year){
  max_time <- length(site_temp)
  site_mean <- mean(site_temp,na.rm = TRUE)
  scaled <- scale(1L:max_time)
  time <- scaled[,1]
  selected.time <- time[n.year]
  loc <- reg_par$weighted_mu0 + reg_par$weighted_mu1 * selected.time + reg_par$weighted_mu2 * selected.time^2
  scale <- (reg_par$weighted_sigma0 + reg_par$weighted_sigma1 * selected.time)
  shape <-  reg_par$weighted_shape

  add.Qt <- as.matrix(extRemes::qevd(prob, loc = loc,
                                        scale = scale,
                                        shape = shape,
                                        type = c("GEV")))
  Qt <- add.Qt + site_mean
  return(Qt)
}
