#' Add_RegProb
#'
#' @param quantiles
#' A numeric vector with no missing data with extreme air temperatures
#' @param reg_par
#' A 6-column and 1-row `data.frame` as that generated by `reg_par()`.
#'  * 1st column is the mu0 parameter,
#'  * 2nd is the mu1 parameter,
#'  * 3rd is the mu2 parameter,
#'  * 4th is the sigma0 parameter,
#'  * 5th is the sigma1 parameter,
#'  * 6th is the shape parameter
#' @param site_temp
#' A vector or 1-column matrix with site's air temperature (original) data.
#' @param n.year
#' A single number describing the number of the year that the time-varying parameters
#' should be calculated. For example, if the users need to calculated the parameters
#' for the first year n.year is set to 1.
#' @export
#' @importFrom extRemes pevd
#' @examples
#' quantiles <- c(39.5,39.8,40.1,40.3,40.4,40.5,40.6,41.0,41.7)
#' reg_par <- regional_pars
#' RegProb <- Add_RegProb(quantiles=quantiles,
#'                   reg_par=reg_par,
#'                   site_temp=dataset$station1,
#'                   n.year=30)

Add_RegProb <- function(quantiles,
                      reg_par,
                      site_temp,
                      n.year){
  max_time <- length(site_temp)
  site_mean <- mean(site_temp,na.rm = TRUE)
  scaled <- scale(1L:max_time)
  time <- scaled[,1]
  selected.time <- time[n.year]
  add.quantiles <- quantiles-site_mean
  loc <- as.numeric(reg_par[1] + reg_par[2] * selected.time + reg_par[3] * selected.time^2)
  scale <- as.numeric(reg_par[4] + reg_par[5] * selected.time)
  shape <-  as.numeric(reg_par[6])

  RegProb <- as.matrix(extRemes::pevd(add.quantiles, loc = loc,
                                   scale = scale,
                                   shape = shape,
                                   type = c("GEV")))
  RegProb[RegProb < 0.0001] <- 0.0001
  RegProb[RegProb > 0.9999] <- 0.9999
  return(RegProb)
}
