#' At-site parameters of a time-varying generalized extreme value distribution
#'
#' At-site parameters of time-varying generalized extreme value distributions
#'  from 15 simulated extreme air temperature series.
#'
#' @format ## `best_sites`
#' A `dataframe` with 7 columns and 15 rows.
#'
#' \describe{
#' \item{mu0}{1st factor of the location parameter for each site}
#' \item{mu1}{2nd factor of the location parameter}
#' \item{mu2}{3rd factor of the location parameter}
#' \item{sigma0}{1st factor of the scale parameter for each site}
#' \item{sigma1}{2nd factor of the scale parameter for each site}
#' \item{shape}{shape parameter for each site}
#' \item{size}{sample size for each site}
#' }
#'
#' @source Generated by statistical simulation using `best_model()`.
"best_sites"
