#' Simulated extreme air temperature data
#'
#' Extreme air temperature data simulated from the Generalized
#' extreme value distribution with parameters fitted from the
#' location of Ribeirao Preto, State of Sao Paulo in Brazil.
#' The data has been divided their sample mean using by `dataset_mult()`.
#' @format ## `divided_data`
#' A matrix with 15 columns and 30 rows. There are missing values.
#'
#' \describe{
#' \item{station1}{scaled extreme air temperature data station 1}
#' \item{station2}{scaled extreme air temperature data station 2}
#' \item{station3}{scaled extreme air temperature data station 3}
#' \item{station4}{scaled extreme air temperature data station 4}
#' \item{station5}{scaled extreme air temperature data station 5}
#' \item{station6}{scaled extreme air temperature data station 6}
#' \item{station7}{scaled extreme air temperature data station 7}
#' \item{station8}{scaled extreme air temperature data station 8}
#' }
#'
#' @source Generated by statistical simulation using the
#'        generalized extreme value distribution.
"divided_data"
