# Generated by roxyglobals: do not edit by hand

utils::globalVariables(c(
  "mu0", # <reg_par>
  "mu1", # <reg_par>
  "mu2", # <reg_par>
  "sigma0", # <reg_par>
  "sigma1", # <reg_par>
  "shape", # <reg_par>
  "size", # <reg_par>
  NULL
))
