#' Mult_RegProb
#'
#' @param quantiles
#' A numeric vector with no missing data with extreme air temperatures
#' @param reg_par
#' A 6-column and 1-row `data.frame` as that generated by `reg_par()`.
#'  * 1st column is the mu0 parameter,
#'  * 2nd is the mu1 parameter,
#'  * 3rd is the mu2 parameter,
#'  * 4th is the sigma0 parameter,
#'  * 5th is the sigma1 parameter,
#'  * 6th is the shape parameter
#' @param site_mean
#' A single number with site's average value for the air temperature data.
#' @param max_time
#' A single number describing the number of the year that the time-varying parameters
#' should be calculated. For example, if the users need to calculated the parameters
#' for the first year max_time is set to 1 and the 30th year max_time is set to 30.
#' @export
#' @importFrom extRemes pevd
#' @examples
#' quantiles <- c(35,35.5,36,36.5,37,37.5,38,38.5,39,39.5,40)
#' reg_par <- regional_pars
#' RegProb <- Mult_RegProb(quantiles=quantiles,
#'                   reg_par=reg_par,
#'                   site_mean=35.9,
#'                   max_time=30)
Mult_RegProb <- function(quantiles,
                        reg_par,
                        site_mean,
                        max_time){
  divided.quantiles <- quantiles/site_mean
  loc <- as.numeric(reg_par[1] + reg_par[2] * max_time + reg_par[3] * max_time^2)
  scale <- as.numeric(reg_par[4] + reg_par[5] * max_time)
  shape <-  as.numeric(reg_par[6])

  RegProb <- as.matrix(extRemes::pevd(divided.quantiles, loc = loc,
                                      scale = scale,
                                      shape = shape,
                                      type = c("GEV")))
  RegProb[RegProb < 0.0001] <- 0.0001
  RegProb[RegProb > 0.9999] <- 0.9999
  return(RegProb)
}
