#' reg_par
#'
#' @param best_model
#' A 7-column `data.frame` as that generated by `best_model()`.
#'  * 1st column is the mu0 parameter,
#'  * 2nd is the mu1 parameter,
#'  * 3rd is the mu2 parameter,
#'  * 4th is the sigma0 parameter,
#'  * 5th is the sigma1 parameter,
#'  * 6th is the shape parameter,
#'  * 7th is the sample size.
#' @returns
#' A `data.frame` with the regional parameters of a
#' time-varying generalized extreme value distribution
#' @export
#' @importFrom dplyr summarise %>%
#' @examples
#' best_model <- best_sites
#' reg_par <- reg_par(best_model=best_model)
reg_par <- function(best_model){
  weighted_means <- best_model %>%
    summarise(
      weighted_mu0 = sum(mu0 * size) / sum(size),
      weighted_mu1 = sum(mu1 * size) / sum(size),
      weighted_mu2 = sum(mu2 * size) / sum(size),
      weighted_sigma0 = sum(sigma0 * size) / sum(size),
      weighted_sigma1 = sum(sigma1 * size) / sum(size),
      weighted_shape = sum(shape * size) / sum(size)
    )
  return(weighted_means)
}
