#' Confidence intervals for site-specific GEV parameters
#'
#' @name Site_parCI
#' @param atsite_temp
#' A numeric vector or single-column matrix of air temperature data.
#' @param model
#' A single integer from 1 to 4 defining the GEV model.
#' @param site_par
#' A 1-row, 5-column data.frame or matrix generated by Fit_model().
#' @param n.boots
#' Number of bootstrap replicates. Values smaller than 100 are not allowed.
#' @return
#' A matrix containing the lower and upper 95% confidence limits of
#' the estimated parameters.
#'
#' @export
#' @importFrom stats quantile
#' @importFrom utils txtProgressBar setTxtProgressBar
#' @examplesIf interactive()
#' temperatures <- TmaxCPC_SP$Pixel_1
#' model <- 2
#' site_par <- Fit_model(temperatures, model)
#'
#' Site_parCI(
#'   atsite_temp = temperatures,
#'   model = model,
#'   site_par = site_par[1:5],
#'   n.boots = 100
#' )
Site_parCI <- function(atsite_temp, model, site_par, n.boots = 999) {
  #----------------------------------------------------------
  # Input checks
  #----------------------------------------------------------

  check_model(model)
  check_n.boots(n.boots)
  data_site <- check_atsite_temp(atsite_temp)
  site_par <- check_site_par(site_par)
  max_time <- length(data_site)

  #----------------------------------------------------------
  # Time-varying parameters (unchanged)
  #----------------------------------------------------------
  time <- seq_len(max_time)
  par.temporal <- matrix(NA_real_, max_time, 3)
  par.temporal[, 1] <- site_par[1] + site_par[2] * time
  par.temporal[, 2] <- site_par[3] + site_par[4] * time
  par.temporal[, 3] <- site_par[5]

  if (any(par.temporal[, 2] <= 0)) {
    stop("The scale parameter becomes non-positive over time.", call. = FALSE)
  }

  #----------------------------------------------------------
  # Transform to Gumbel space (unchanged)
  #----------------------------------------------------------
  if (abs(site_par[5]) < sqrt(.Machine$double.eps)) {
    IDD.series <- (data_site - par.temporal[, 1]) / par.temporal[, 2]
  } else {
    z <- 1 +
      par.temporal[, 3] * ((data_site - par.temporal[, 1]) / par.temporal[, 2])
    if (any(z <= 0, na.rm = TRUE)) {
      stop("Invalid transformed values encountered.", call. = FALSE)
    }
    IDD.series <- (1 / par.temporal[, 3]) * log(z)
  }

  #----------------------------------------------------------
  # CHANGE 1: Pre-generate all bootstrap indices at once
  # sample.int() is faster than sample() on a plain index vector,
  # and doing it in one call avoids n.boots separate RNG invocations.
  #----------------------------------------------------------
  boot_indices <- matrix(
    sample.int(max_time, size = max_time * n.boots, replace = TRUE),
    nrow = max_time, # each column = one bootstrap replicate
    ncol = n.boots
  )

  #----------------------------------------------------------
  # CHANGE 2: Pre-compute the back-transformation constants outside the loop.
  # These vectors are the same every iteration — no need to recompute them.
  #----------------------------------------------------------
  use_gumbel <- abs(site_par[5]) < sqrt(.Machine$double.eps)
  mu_vec <- par.temporal[, 1] # length max_time
  sigma_vec <- par.temporal[, 2]
  xi <- site_par[5]

  site_par.overall.boot <- matrix(NA_real_, nrow = n.boots, ncol = 5)

  message("This calculation may take some time.")
  show_pb <- interactive()
  if (show_pb) {
    pb <- txtProgressBar(min = 0, max = n.boots, style = 3)
  }

  #----------------------------------------------------------
  # Bootstrap loop — Fit_model() calls are irreducible, but
  # everything else inside is now leaner.
  #----------------------------------------------------------
  for (r in seq_len(n.boots)) {
    # CHANGE 3: index directly from the pre-built matrix — no arithmetic,
    # no large flat vector to subset
    resampled_IDD <- IDD.series[boot_indices[, r]]

    # CHANGE 4: back-transformation is the same vectorised ops as before,
    # but now uses pre-extracted scalars/vectors (avoids repeated [,] indexing)
    if (use_gumbel) {
      back.orig <- mu_vec + sigma_vec * resampled_IDD
    } else {
      back.orig <- mu_vec + (sigma_vec / xi) * (exp(resampled_IDD * xi) - 1)
    }

    parameters <- Fit_model(temperatures = back.orig, model = model)
    site_par.overall.boot[r, ] <- as.numeric(parameters[1, 1:5, drop = FALSE])

    if (show_pb) setTxtProgressBar(pb, r)
  }

  if (show_pb) {
    close(pb)
  }

  #----------------------------------------------------------
  # CHANGE 5: matrixStats::colQuantiles() is significantly faster than
  # two apply() calls for large n.boots — avoids repeated overhead.
  # Falls back gracefully if the package isn't available.
  #----------------------------------------------------------
  if (requireNamespace("matrixStats", quietly = TRUE)) {
    qs <- matrixStats::colQuantiles(
      site_par.overall.boot,
      probs = c(0.025, 0.975),
      na.rm = TRUE
    )
    CI_lower <- qs[1, ]
    CI_upper <- qs[2, ]
  } else {
    CI_lower <- apply(
      site_par.overall.boot,
      2,
      quantile,
      probs = 0.025,
      na.rm = TRUE
    )
    CI_upper <- apply(
      site_par.overall.boot,
      2,
      quantile,
      probs = 0.975,
      na.rm = TRUE
    )
  }

  CI_matrix <- rbind(CI_lower, CI_upper)
  rownames(CI_matrix) <- c("Lower 95% CI", "Upper 95% CI")
  colnames(CI_matrix) <- c("mu0", "mu1", "sigma0", "sigma1", "shape")
  return(CI_matrix)
}
